jobs:

  - template: azure-pipelines-windows-buildwheel-template.yml
    parameters:
      name: 'win_py310'
      vmImage: 'windows-2022'
      CIBW_BUILD: 'cp310-*'
      NUMPY_VERSION: '2.0.0'

  - template: azure-pipelines-windows-buildwheel-template.yml
    parameters:
      name: 'win_py311'
      vmImage: 'windows-2022'
      CIBW_BUILD: 'cp311-*'
      NUMPY_VERSION: '2.0.0'

  - template: azure-pipelines-windows-buildwheel-template.yml
    parameters:
      name: 'win_py312'
      vmImage: 'windows-2022'
      CIBW_BUILD: 'cp312-*'
      NUMPY_VERSION: '2.0.0'

  - template: azure-pipelines-windows-buildwheel-template.yml
    parameters:
      name: 'win_py313'
      vmImage: 'windows-2022'
      CIBW_BUILD: 'cp313-*'
      NUMPY_VERSION: '2.1.3'

  - template: azure-pipelines-windows-buildwheel-template.yml
    parameters:
      name: 'win_py314'
      vmImage: 'windows-2022'
      CIBW_BUILD: 'cp314-*'
      NUMPY_VERSION: '2.3.2'
      force: true
